site_name: Victorien Djontso - CV
site_url: https://dvrch.github.io/victorien-djontso-cv/
site_description: CV de Victorien Djontso

repo_url: https://github.com/dvrch/victorien-djontso-cv

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.sections
    - search.highlight
    - content.tabs.link
    - navigation.instant
  icon:
    logo: material/book-open-variant

nav:
  - Accueil: index.md
  - English CV: cv-en.md
  - Réalisations: achievements.md
  - CV Imprimable: cv-imprimable.md
  - Configuration MkDocs: mkdocs-setup.md
  - GitHub Actions: github-actions-basics.md
  - Problèmes courants: common-issues-and-solutions.md
  - Sujets avancés: advanced-topics.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed: {alternate_style: true}
  - attr_list
  - md_in_html
  - pymdownx.magiclink

plugins:
  - search

docs_dir: svelte-3d-viewer/src/lib/content
site_dir: site