site_name: Victorien Djontso - CV
site_url: https://dvrch.github.io/victorien-djontso-cv/
site_description: CV de Victorien Djontso

repo_url: https://github.com/dvrch/victorien-djontso-cv

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.sections
    - search.highlight
    - content.tabs.link
    - navigation.instant
  icon:
    logo: material/book-open-variant

nav:
  - Accueil: index.html
  - English CV: cv_en.html
  - Réalisations: achievements.html
  - CV Imprimable: cv_imprimable.html

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed: {alternate_style: true}
  - attr_list
  - md_in_html
  - pymdownx.magiclink

plugins:
  - search

docs_dir: docs
site_dir: site